### ISSUE TITLE
Create theRADlist map/list 

### ISSUE THREAD

**Issue by askalburgi** [theradlist/theradlist.github.io#2]
d3 map
accompanied by a list (on the side) the top 5 spots in the map view (update on zoom) 

click on item in map or on list => pops up info about it/w.e

**Comment by askalburgi** [comment]
Design, map with radial border gradient. White themed map where blocks representing restraunts should are Cinnabar

**Comment by abidrahman** [comment]
- https://bl.ocks.org/mbostock/899711
- https://hackernoon.com/d3-js-and-google-maps-api-in-10-easy-steps-4f258323525b
-
